# Generated by Django 3.0.1 on 2021-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prioritization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('issue_key', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('priority_number', models.IntegerField()),
                ('case_title', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
                ('sprint', models.CharField(max_length=50)),
                ('due_date', models.CharField(max_length=50)),
                ('sys_fiscal_week', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=50)),
                ('a', models.CharField(max_length=50)),
                ('project_size', models.CharField(max_length=50)),
                ('report_table', models.CharField(max_length=50)),
                ('request_item', models.CharField(max_length=100)),
                ('request_owner', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
                ('objective', models.IntegerField(unique=True)),
            ],
        ),
    ]
