# Generated by Django 3.0.1 on 2021-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210823_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritization',
            name='rowid',
            field=models.IntegerField(default=1),
        ),
    ]
